export const oldListing = {
  _id: "68cb0862ee7b3ba687972299",
  social: [
    { fieldname: "URL", value: "Toronto Marriott City Centre Hotel", smfieldid: 7, smserviceid: 4 },
    { fieldname: "URL", value: "torontomarriottcc", smfieldid: 7, smserviceid: 13 },
    { fieldname: "URL", value: "torontomarriottcc", smfieldid: 7, smserviceid: 24 },
  ],
  taid: 155586,
  taoptin: false,
  zip: "M5V 1J1",
  contact_email: "erin.dumont@larcohotels.com",
  address1: "1 Blue Jays Way",
  media: [
    {
      mediaid: 17280,
      mediafile: "original_MH_YYZCC_Concierge_King_E40F06D8-5919-47D8-8F38F3AFE8255657.jpg",
      mediaurl: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/MH_YYZCC_Concierge_King_E40F06D8-5919-47D8-8F38F3AFE8255657_73ed5b10-2c9b-456e-9a41318505171d6d.jpg",
      sortorder: 1,
      mediathumburl: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/MH_YYZCC_Concierge_King_E40F06D8-5919-47D8-8F38F3AFE8255657_73ed5b10-2c9b-456e-9a41318505171d6d.jpg",
      medianame: "Concierge King",
      mediatype: "Image",
    },
    {
      mediathumbfile: "thumb_Renaissance_Pool_09370.jpg",
      mediaid: 7890,
      mediafile: "original_Renaissance_Pool_09370.jpg",
      mediaurl: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/Renaissance_Pool_09370_5eeb7443-5056-a36f-23f393c57853c761.jpg",
      sortorder: 2,
      mediathumburl: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/Renaissance_Pool_09370_5eeb7443-5056-a36f-23f393c57853c761.jpg",
      medianame: "Our Pool",
      mediatype: "Image",
    },
    {
      mediathumbfile: "thumb_renaissance_Gym_08710.jpg",
      mediaid: 7891,
      mediafile: "original_renaissance_Gym_08710.jpg",
      mediaurl: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/renaissance_Gym_08710_5eeb6bd5-5056-a36f-23d966a7f42e1ff4.jpg",
      sortorder: 3,
      mediathumburl: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/renaissance_Gym_08710_5eeb6bd5-5056-a36f-23d966a7f42e1ff4.jpg",
      medianame: "Our Gym",
      mediatype: "Image",
    },
    {
      mediaid: 14513,
      mediafile: "original_MH_YYZCC_SPORTSNET_Bar_8DC764FB-A4AA-4754-BE8D37DF5EDE2FC5.jpg",
      mediaurl: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/MH_YYZCC_SPORTSNET_Bar_8DC764FB-A4AA-4754-BE8D37DF5EDE2FC5_4d6910ae-9798-4fb1-8ed2300d598c374a.jpg",
      sortorder: 5,
      mediathumburl: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/MH_YYZCC_SPORTSNET_Bar_8DC764FB-A4AA-4754-BE8D37DF5EDE2FC5_4d6910ae-9798-4fb1-8ed2300d598c374a.jpg",
      medianame: "Sportsnet Grill",
      mediatype: "Image",
    },
    {
      mediaid: 17281,
      mediafile: "original_MH_YYZCC_Standard_Double_CityView_View_6BC841BC-9A84-4ABB-8E8262E86781B1D9.jpg",
      mediaurl: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/MH_YYZCC_Standard_Double_CityView_View_6BC841BC-9A84-4ABB-8E8262E86781B1D9_229c819e-b715-4250-9c91a574a52344e4.jpg",
      sortorder: 6,
      mediathumburl: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/MH_YYZCC_Standard_Double_CityView_View_6BC841BC-9A84-4ABB-8E8262E86781B1D9_229c819e-b715-4250-9c91a574a52344e4.jpg",
      medianame: "Standard Double Cityview Room",
      mediatype: "Image",
    },
    {
      mediaid: 17282,
      mediafile: "original_008_Northem-Light-Ballroom-Theatre-Set-Up_6161_42DD2AAA-245E-427E-86D1543B78B41AF4.jpg",
      mediaurl: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/008_Northem-Light-Ballroom-Theatre-Set-Up_6161_42DD2AAA-245E-427E-86D1543B78B41AF4_a5ff22e9-8431-4064-bfd18949526045b5.jpg",
      sortorder: 7,
      mediathumburl: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/008_Northem-Light-Ballroom-Theatre-Set-Up_6161_42DD2AAA-245E-427E-86D1543B78B41AF4_a5ff22e9-8431-4064-bfd18949526045b5.jpg",
      medianame: "Northern Lights Ballroom",
      mediatype: "Image",
    },
    {
      mediaid: 17283,
      mediafile: "original_010_Aurora-Room_6351_E97FD0B0-EBBA-44A8-B88A941E13E25B13.jpg",
      mediaurl: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/010_Aurora-Room_6351_E97FD0B0-EBBA-44A8-B88A941E13E25B13_52e91dd0-2479-44a8-becfc6b571e30b7d.jpg",
      sortorder: 8,
      mediathumburl: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/010_Aurora-Room_6351_E97FD0B0-EBBA-44A8-B88A941E13E25B13_52e91dd0-2479-44a8-becfc6b571e30b7d.jpg",
      medianame: "Aurora Room",
      mediatype: "Image",
    },
    {
      mediaid: 18058,
      mediafile: "original_MH_YYZCC_Split_Level_1Queen_Fieldview_879A3FC3-A1BC-4941-AFE07569A7F7049B.jpg",
      mediaurl: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/MH_YYZCC_Split_Level_1Queen_Fieldview_879A3FC3-A1BC-4941-AFE07569A7F7049B_311e1ca3-4cce-4cc4-bbf741f7700a9968.jpg",
      sortorder: 10,
      mediathumburl: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/MH_YYZCC_Split_Level_1Queen_Fieldview_879A3FC3-A1BC-4941-AFE07569A7F7049B_311e1ca3-4cce-4cc4-bbf741f7700a9968.jpg",
      medianame: "Fieldview Room",
      mediatype: "Image",
    },
    {
      mediaid: 18059,
      mediafile: "original_MH_YYZCC_Standard_King_Fieldview_89BF8F29-AE79-4DDF-B3D8E23861D45516.jpg",
      mediaurl: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/MH_YYZCC_Standard_King_Fieldview_89BF8F29-AE79-4DDF-B3D8E23861D45516_e49a51f2-5b10-445d-a962780935e8d0d1.jpg",
      sortorder: 11,
      mediathumburl: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/MH_YYZCC_Standard_King_Fieldview_89BF8F29-AE79-4DDF-B3D8E23861D45516_e49a51f2-5b10-445d-a962780935e8d0d1.jpg",
      medianame: "Fieldview Standard",
      mediatype: "Image",
    },
  ],
  region: "City Center",
  fax: "416-341-5091",
  typeid: 16,
  company: "Toronto Marriott City Centre Hotel",
  listingudfs: [
    {
      name: "Shortlisting",
      value: "The world's first and only 348 guestroom hotel connected to a domed sports and entertainment facility with 70 rooms overlooking the stadium and field. Over 13,000 square feet of flexible meeting space is available along with four Skyboxes for ...",
      digits: 0,
      fieldid: 4007,
      typeid: 9,
      type: "Text Area",
      value_raw: "The world's first and only 348 guestroom hotel connected to a domed sports and entertainment facility with 70 rooms overlooking the stadium and field. Over 13,000 square feet of flexible meeting space is available along with four Skyboxes for ...",
      value_string: "The world's first and only 348 guestroom hotel connected to a domed sports and entertainment facility with 70 rooms overlooking the stadium and field. Over 13,000 square feet of flexible meeting space is available along with four Skyboxes for ...",
    },
    {
      name: "Randomized Listing Order",
      value: 1404,
      digits: 0,
      fieldid: 4816,
      typeid: 4,
      type: "Number",
      value_raw: 1404,
      value_string: "1404",
    },
  ],
  altphone: "1 800 237-1512",
  tacatid: 1,
  accountudfs: [
    { listid: 969, name: "RTO", value: "RTO - T", digits: 0, fieldid: 4029, typeid: 7, type: "Dropdown", value_raw: { listid: 969, value: "RTO - T" }, value_string: "RTO - T" },
    { listid: 2531, name: "Membership Type", value: "Business Membership", digits: 0, fieldid: 4801, typeid: 7, type: "Dropdown", value_raw: { listid: 2531, value: "Business Membership" }, value_string: "Business Membership" },
    { listid: 2108, name: "Membership Pipeline", value: "Renewed", digits: 0, fieldid: 4839, typeid: 7, type: "Dropdown", value_raw: { listid: 2108, value: "Renewed" }, value_string: "Renewed" },
    { listid: 2664, name: "Primary Business Type", value: "Accommodations", digits: 0, fieldid: 4977, typeid: 7, type: "Dropdown", value_raw: { listid: 2664, value: "Accommodations" }, value_string: "Accommodations" },
  ],
  description: "The world's first and only 4 diamond hotel connected to a domed sports and entertainment facility with 55 rooms overlooking the stadium and field. Over 13,000 square feet of flexible meeting space is available along with four Skyboxes for groups of up to 30. You will find this property next to the Metro Toronto Convention Centre, the CN Tower and Ripley's Aquarium. On the edge of Toronto's financial core and in the heart of the entertainment district. Where business and pleasure meet.",
  fullname: "Erin Dumont",
  city: "Toronto",
  acctid: 37,
  sortcompany: "toronto marriott city centre hotel",
  typename: "Content Hub Listing",
  rankorder: 1,
  state: "ON",
  fname: "Erin",
  recid: 29178,
  weburl: "https://www.marriott.com/hotels/travel/yyzcc-toronto-marriott-city-centre-hotel/",
  status: "Active",
  meetingfacility: {
    additional: [
      { tabshortname: "custommeetingfacilities", amenitytabid: 999, value: "4066", label: "Total Sq. Ft. Ballroom", shortname: "ballroomsize", amenitygroupid: 2, digits: 1, fieldid: 114, typeid: 4, type: "Number", value_raw: 4066, value_string: "4066.0" },
      { tabshortname: "custommeetingfacilities", amenitytabid: 999, value: "true", label: "Exhibit Space", shortname: "exhibitspace", amenitygroupid: 2, digits: 0, fieldid: 115, typeid: 11, type: "Yes/No", value_raw: true, value_string: "Yes" },
      { tabshortname: "custommeetingfacilities", amenitytabid: 999, value: "https://www.marriott.com/en-us/hotels/yyzcc-toronto-marriott-city-centre-hotel/events/", label: "Floorplan (URL)", shortname: "floorplan", amenitygroupid: 2, digits: 0, fieldid: 56, typeid: 10, type: "URL", value_raw: "https://www.marriott.com/en-us/hotels/yyzcc-toronto-marriott-city-centre-hotel/events/", value_string: "https://www.marriott.com/en-us/hotels/yyzcc-toronto-marriott-city-centre-hotel/events/" },
      { tabshortname: "custommeetingfacilities", amenitytabid: 999, value: "4066", label: "Largest Room Sq. Ft.", shortname: "largestroomsize", amenitygroupid: 2, digits: 1, fieldid: 113, typeid: 4, type: "Number", value_raw: 4066, value_string: "4066.0" },
      { tabshortname: "custommeetingfacilities", amenitytabid: 999, value: "12224", label: "Total Meeting Space Sq. Ft.", shortname: "meetingspacesize", amenitygroupid: 2, digits: 1, fieldid: 112, typeid: 4, type: "Number", value_raw: 12224, value_string: "12224.0" },
      { tabshortname: "custommeetingfacilities", amenitytabid: 999, value: "10", label: "Number of Meeting Rooms", shortname: "totalmeetingrooms", amenitygroupid: 2, digits: 0, fieldid: 111, typeid: 4, type: "Number", value_raw: 10, value_string: "10" },
      { listid: 17, tabshortname: "custommeetingfacilities", amenitytabid: 999, value: "100-199", label: "Guest Capacity", shortname: "guestcapacity", amenitygroupid: 2, digits: 0, fieldid: 126, typeid: 7, type: "Dropdown", value_raw: { listid: 17, value: "100-199" }, value_string: "100-199" },
    ],
    exhibitspace: 1,
    numrooms: 10,
    largestroom: 4066,
    totalsqft: 12224,
    additional_object: {
      ballroomsize: { value: "4066", label: "Total Sq. Ft. Ballroom", shortname: "ballroomsize", fieldid: 114, typeid: 4, type: "Number", value_raw: 4066, value_string: "4066.0" },
      exhibitspace: { value: "true", label: "Exhibit Space", shortname: "exhibitspace", fieldid: 115, typeid: 11, type: "Yes/No", value_raw: true, value_string: "Yes" },
      floorplan: { value: "https://www.marriott.com/en-us/hotels/yyzcc-toronto-marriott-city-centre-hotel/events/", label: "Floorplan (URL)", shortname: "floorplan", fieldid: 56, typeid: 10, type: "URL", value_raw: "https://www.marriott.com/en-us/hotels/yyzcc-toronto-marriott-city-centre-hotel/events/", value_string: "https://www.marriott.com/en-us/hotels/yyzcc-toronto-marriott-city-centre-hotel/events/" },
      largestroomsize: { value: "4066", label: "Largest Room Sq. Ft.", shortname: "largestroomsize", fieldid: 113, typeid: 4, type: "Number", value_raw: 4066, value_string: "4066.0" },
      meetingspacesize: { value: "12224", label: "Total Meeting Space Sq. Ft.", shortname: "meetingspacesize", fieldid: 112, typeid: 4, type: "Number", value_raw: 12224, value_string: "12224.0" },
      totalmeetingrooms: { value: "10", label: "Number of Meeting Rooms", shortname: "totalmeetingrooms", fieldid: 111, typeid: 4, type: "Number", value_raw: 10, value_string: "10" },
      guestcapacity: { listid: 17, value: "100-199", label: "Guest Capacity", shortname: "guestcapacity", fieldid: 126, typeid: 7, type: "Dropdown", value_raw: { listid: 17, value: "100-199" }, value_string: "100-199" },
    },
  },
  phone: "416 341-7100",
  addressid: 17,
  amenities_array: [
    { tabshortname: "general", amenitytabid: 1, value: "true", label: "Delivery Available", shortname: "deliveryavailable", amenitygroupid: 33, digits: 0, fieldid: 286, typeid: 11, type: "Yes/No", value_raw: true, value_string: "Yes", uniquename: "general_deliveryavailable" },
    { tabshortname: "general", amenitytabid: 1, value: "true", label: "Full Buyouts", shortname: "fullbuyouts", amenitygroupid: 33, digits: 0, fieldid: 308, typeid: 11, type: "Yes/No", value_raw: true, value_string: "Yes", uniquename: "general_fullbuyouts" },
    { tabshortname: "general", amenitytabid: 1, value: "true", label: "Patio Dining", shortname: "patiodining", amenitygroupid: 33, digits: 0, fieldid: 277, typeid: 11, type: "Yes/No", value_raw: true, value_string: "Yes", uniquename: "general_patiodining" },
    { tabshortname: "general", amenitytabid: 1, value: "true", label: "Private Dining Space", shortname: "privatediningspace", amenitygroupid: 33, digits: 0, fieldid: 306, typeid: 11, type: "Yes/No", value_raw: true, value_string: "Yes", uniquename: "general_privatediningspace" },
    { tabshortname: "general", amenitytabid: 1, value: "150", label: "Capacity of Private Dining Space", shortname: "privatediningspacecapacity", amenitygroupid: 33, digits: 0, fieldid: 307, typeid: 8, type: "Text", value_raw: "150", value_string: "150", uniquename: "general_privatediningspacecapacity" },
    { tabshortname: "accommodations", amenitytabid: 1009, value: "true", label: "Does your property have a fitness centre?", shortname: "fitnesscentre", amenitygroupid: 18, digits: 0, fieldid: 110, typeid: 11, type: "Yes/No", value_raw: true, value_string: "Yes", uniquename: "accommodations_fitnesscentre" },
    { tabshortname: "accommodations", amenitytabid: 1009, value: "true", label: "Does your property have a pool?", shortname: "pool", amenitygroupid: 18, digits: 0, fieldid: 107, typeid: 11, type: "Yes/No", value_raw: true, value_string: "Yes", uniquename: "accommodations_pool" },
    { listid: 14, tabshortname: "accommodations", amenitytabid: 1009, value: "Indoor", label: "Pool location", shortname: "location", amenitygroupid: 18, digits: 0, fieldid: 109, typeid: 7, type: "Dropdown", value_raw: { listid: 14, value: "Indoor" }, value_string: "Indoor", uniquename: "accommodations_location" },
  ],
  rankname: "Member",
  crmtracking: {
    core_itinerary: "58_29178",
    core_booking_click: "7_29178",
    custom_referrals_bookdirect_lodging: "112_29178",
    core_map_view: "59_29178",
    core_listing_view: "1_29178",
    core_mobile_view: "17_29178",
    custom_threshold_360_views: "120_29178",
    custom_instagram_views: "114_29178",
    custom_visitapps_listing_view: "111_29178",
    custom_referrals_bandwango: "124_29178",
    custom_referrals_bookdirect_activities: "113_29178",
    core_twitter_view: "12_29178",
    core_mobile_click: "16_29178",
    custom_referrals_ticketmaster: "123_29178",
    custom_core_placeholder: "125_29178",
    core_listing_click: "4_29178",
    custom_visitapps_passport_check_in: "110_29178",
    custom_ticketed_event_referrals: "122_29178",
    custom_instagram_click_thrus: "115_29178",
    core_facebook_view: "14_29178",
    custom_youtube_click_thrus: "117_29178",
    core_mobile_call: "18_29178",
    core_facebook_click: "15_29178",
    custom_youtube_views: "116_29178",
    custom_referrals_viator: "121_29178",
    custom_pinterest_views: "118_29178",
    custom_pinterest_click_thrus: "119_29178",
    core_twitter_click: "13_29178",
  },
  country: "CANADA",
  tollfree: "1-800-237-1512",
  lname: "Dumont",
  rankid: 6,
  meetingrooms: [
    { roomname: "Northern Lights Ballroom", roomid: "1596", banquet: "250", height: "14", udfs: [{ name: "U-Shape Capacity", value: 45, digits: 0, fieldid: 4538, typeid: 4, type: "Number", value_raw: 45, value_string: "45" }], classroom: "150", reception: "300", theater: "320", sqft: "4066", udfs_object: { 4538: { name: "U-Shape Capacity", value: 45, digits: 0, fieldid: 4538, typeid: 4, type: "Number", value_raw: 45, value_string: "45" } } },
    { roomname: "Aurora Room", roomid: "1597", banquet: "120", height: "14", udfs: [{ name: "U-Shape Capacity", value: 36, digits: 0, fieldid: 4538, typeid: 4, type: "Number", value_raw: 36, value_string: "36" }, { name: "Boardroom capacity", value: 28, digits: 0, fieldid: 4539, typeid: 4, type: "Number", value_raw: 28, value_string: "28" }], classroom: "48", reception: "150", theater: "80", sqft: "2110", udfs_object: { 4538: { name: "U-Shape Capacity", value: 36, digits: 0, fieldid: 4538, typeid: 4, type: "Number", value_raw: 36, value_string: "36" }, 4539: { name: "Boardroom capacity", value: 28, digits: 0, fieldid: 4539, typeid: 4, type: "Number", value_raw: 28, value_string: "28" } } },
    { roomname: "Blue Jays Room", roomid: "1599", banquet: "56", height: "10", udfs: [{ name: "U-Shape Capacity", value: 24, digits: 0, fieldid: 4538, typeid: 4, type: "Number", value_raw: 24, value_string: "24" }, { name: "Boardroom capacity", value: 20, digits: 0, fieldid: 4539, typeid: 4, type: "Number", value_raw: 20, value_string: "20" }], classroom: "42", reception: "80", theater: "70", sqft: "1308" },
    { roomname: "Raptor Room", roomid: "1600", banquet: "64", height: "10", udfs: [{ name: "U-Shape Capacity", value: 36, digits: 0, fieldid: 4538, typeid: 4, type: "Number", value_raw: 36, value_string: "36" }, { name: "Boardroom capacity", value: 40, digits: 0, fieldid: 4539, typeid: 4, type: "Number", value_raw: 40, value_string: "40" }], classroom: "60", reception: "80", theater: "100", sqft: "1185" },
    { roomname: "Maple Leaf Room", roomid: "1601", banquet: "32", height: "10", udfs: [{ name: "U-Shape Capacity", value: 18, digits: 0, fieldid: 4538, typeid: 4, type: "Number", value_raw: 18, value_string: "18" }, { name: "Boardroom capacity", value: 24, digits: 0, fieldid: 4539, typeid: 4, type: "Number", value_raw: 24, value_string: "24" }], classroom: "24", reception: "40", theater: "40", sqft: "640" },
    { roomname: "SkyBox 1", roomid: "1602", banquet: "32", height: "8", udfs: [{ name: "U-Shape Capacity", value: 18, digits: 0, fieldid: 4538, typeid: 4, type: "Number", value_raw: 18, value_string: "18" }, { name: "Boardroom capacity", value: 10, digits: 0, fieldid: 4539, typeid: 4, type: "Number", value_raw: 10, value_string: "10" }], classroom: "24", reception: "25", theater: "10", sqft: "469" },
    { roomname: "SkyBox 2", roomid: "1603", banquet: "32", height: "7", udfs: [{ name: "U-Shape Capacity", value: 18, digits: 0, fieldid: 4538, typeid: 4, type: "Number", value_raw: 18, value_string: "18" }, { name: "Boardroom capacity", value: 10, digits: 0, fieldid: 4539, typeid: 4, type: "Number", value_raw: 10, value_string: "10" }], classroom: "24", reception: "25", theater: "10", sqft: "450" },
    { roomname: "SkyBox 3", roomid: "1604", banquet: "32", height: "7", udfs: [{ name: "U-Shape Capacity", value: 18, digits: 0, fieldid: 4538, typeid: 4, type: "Number", value_raw: 18, value_string: "18" }, { name: "Boardroom capacity", value: 12, digits: 0, fieldid: 4539, typeid: 4, type: "Number", value_raw: 12, value_string: "12" }], classroom: "24", reception: "25", theater: "12", sqft: "444" },
    { roomname: "SkyBox 4", roomid: "1605", banquet: "32", height: "8", udfs: [{ name: "U-Shape Capacity", value: 18, digits: 0, fieldid: 4538, typeid: 4, type: "Number", value_raw: 18, value_string: "18" }, { name: "Boardroom capacity", value: 16, digits: 0, fieldid: 4539, typeid: 4, type: "Number", value_raw: 16, value_string: "16" }], classroom: "24", reception: "30", theater: "16", sqft: "572" },
    { roomname: "Legends Lounge", roomid: "1606", banquet: "50", height: "8", udfs: [{ name: "U-Shape Capacity", value: 18, digits: 0, fieldid: 4538, typeid: 4, type: "Number", value_raw: 18, value_string: "18" }, { name: "Boardroom capacity", value: 16, digits: 0, fieldid: 4539, typeid: 4, type: "Number", value_raw: 16, value_string: "16" }], classroom: "24", reception: "60", theater: "16", sqft: "980" },
  ],
  contactid: 5913,
  addresstype: "Physical",
  statusid: 1639,
  categories: [
    { primary: true, subcatid: 2670, subcatname: "Hotels", catname: "Accommodations", catid: 226, threshold360id: "8453331", parentid: 14565, title: "Toronto Marriott City Centre Hotel", regionid: 100 },
  ],
  social_object: {
    Facebook: [{ fieldname: "URL", value: "Toronto Marriott City Centre Hotel", smfieldid: 7, smserviceid: 4 }],
    Instagram: [{ fieldname: "URL", value: "torontomarriottcc", smfieldid: 7, smserviceid: 13 }],
    TikTok: [{ fieldname: "URL", value: "torontomarriottcc", smfieldid: 7, smserviceid: 24 }],
  },
  listingudfs_object: {
    4007: { name: "Shortlisting", value: "The world's first and only 348 guestroom hotel connected to a domed sports and entertainment facility with 70 rooms overlooking the stadium and field. Over 13,000 square feet of flexible meeting space is available along with four Skyboxes for ...", digits: 0, fieldid: 4007, typeid: 9, type: "Text Area", value_raw: "The world's first and only 348 guestroom hotel connected to a domed sports and entertainment facility with 70 rooms overlooking the stadium and field. Over 13,000 square feet of flexible meeting space is available along with four Skyboxes for ...", value_string: "The world's first and only 348 guestroom hotel connected to a domed sports and entertainment facility with 70 rooms overlooking the stadium and field. Over 13,000 square feet of flexible meeting space is available along with four Skyboxes for ..." },
    4816: { name: "Randomized Listing Order", value: 1404, digits: 0, fieldid: 4816, typeid: 4, type: "Number", value_raw: 1404, value_string: "1404" },
  },
  accountudfs_object: {
    4029: { listid: 969, name: "RTO", value: "RTO - T", digits: 0, fieldid: 4029, typeid: 7, type: "Dropdown", value_raw: { listid: 969, value: "RTO - T" }, value_string: "RTO - T" },
    4801: { listid: 2531, name: "Membership Type", value: "Business Membership", digits: 0, fieldid: 4801, typeid: 7, type: "Dropdown", value_raw: { listid: 2531, value: "Business Membership" }, value_string: "Business Membership" },
    4839: { listid: 2108, name: "Membership Pipeline", value: "Renewed", digits: 0, fieldid: 4839, typeid: 7, type: "Dropdown", value_raw: { listid: 2108, value: "Renewed" }, value_string: "Renewed" },
    4977: { listid: 2664, name: "Primary Business Type", value: "Accommodations", digits: 0, fieldid: 4977, typeid: 7, type: "Dropdown", value_raw: { listid: 2664, value: "Accommodations" }, value_string: "Accommodations" },
  },
  amenities: {
    general_deliveryavailable: { value: "true", label: "Delivery Available", shortname: "deliveryavailable", fieldid: 286, typeid: 11, type: "Yes/No", value_raw: true, value_string: "Yes", uniquename: "general_deliveryavailable" },
    general_fullbuyouts: { value: "true", label: "Full Buyouts", shortname: "fullbuyouts", fieldid: 308, typeid: 11, type: "Yes/No", value_raw: true, value_string: "Yes", uniquename: "general_fullbuyouts" },
    general_patiodining: { value: "true", label: "Patio Dining", shortname: "patiodining", fieldid: 277, typeid: 11, type: "Yes/No", value_raw: true, value_string: "Yes", uniquename: "general_patiodining" },
    general_privatediningspace: { value: "true", label: "Private Dining Space", shortname: "privatediningspace", fieldid: 306, typeid: 11, type: "Yes/No", value_raw: true, value_string: "Yes", uniquename: "general_privatediningspace" },
    general_privatediningspacecapacity: { value: "150", label: "Capacity of Private Dining Space", shortname: "privatediningspacecapacity", fieldid: 307, typeid: 8, type: "Text", value_raw: "150", value_string: "150", uniquename: "general_privatediningspacecapacity" },
    accommodations_fitnesscentre: { value: "true", label: "Does your property have a fitness centre?", shortname: "fitnesscentre", fieldid: 110, typeid: 11, type: "Yes/No", value_raw: true, value_string: "Yes", uniquename: "accommodations_fitnesscentre" },
    accommodations_pool: { value: "true", label: "Does your property have a pool?", shortname: "pool", fieldid: 107, typeid: 11, type: "Yes/No", value_raw: true, value_string: "Yes", uniquename: "accommodations_pool" },
    accommodations_location: { listid: 14, value: "Indoor", label: "Pool location", shortname: "location", fieldid: 109, typeid: 7, type: "Dropdown", value_raw: { listid: 14, value: "Indoor" }, value_string: "Indoor", uniquename: "accommodations_location" },
  },
  updated: "2026-06-17T08:17:59.845Z",
  contacttitle: "Lead Catcher/Sales Coordinator",
  alpha: "t",
  loc: { type: "Point", coordinates: [-79.3891419, 43.641804] },
  sites: ["primary", "maps", "splash", "meetings", "rto5", "inc"],
  primary_site: "primary",
  primary_category: { primary: true, subcatid: 2670, subcatname: "Hotels", catname: "Accommodations", catid: 226 },
  primarycatid: 226,
  primarysubcatid: 2670,
  cms_title: "Toronto Marriott City Centre Hotel - Accommodations - Hotels (29178)",
  cms_title_sort: "toronto marriott city centre hotel - accommodations - hotels (29178)",
  primary_image_url: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/MH_YYZCC_Concierge_King_E40F06D8-5919-47D8-8F38F3AFE8255657_73ed5b10-2c9b-456e-9a41318505171d6d.jpg",
  primary_image_is_default: false,
  filter_tags: [
    "site_primary",
    "catid_226",
    "subcatid_2670",
    "site_primary_catid_226",
    "site_primary_subcatid_2670",
    "site_primary_catid_226_subcatid_2670",
    "site_maps",
    "site_maps_catid_226",
    "site_maps_subcatid_2670",
    "site_maps_catid_226_subcatid_2670",
    "site_splash",
    "site_splash_catid_226",
    "site_splash_subcatid_2670",
    "site_splash_catid_226_subcatid_2670",
    "site_meetings",
    "site_meetings_catid_226",
    "site_meetings_subcatid_2670",
    "site_meetings_catid_226_subcatid_2670",
    "site_rto5",
    "site_rto5_catid_226",
    "site_rto5_subcatid_2670",
    "site_rto5_catid_226_subcatid_2670",
    "site_inc",
    "site_inc_catid_226",
    "site_inc_subcatid_2670",
    "site_inc_subcatid_2670",
    "site_inc_catid_226_subcatid_2670",
  ],
  qualityScore: -1,
};
